coverage:
  paths:
    - cover.out
comment:
  if: is_pull_request
  deletePrevious: true
summary:
  if: true
report:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
diff:
  datastores:
    - artifact://${GITHUB_REPOSITORY}
codeToTestRatio:
  code:
    - "**/*.go"
  test:
    - "**/*_test.go"