// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.8
// 	protoc        (unknown)
// source: atelerix.proto

package emitterproto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type HealthCheckResponse_ServingStatus int32

const (
	HealthCheckResponse_UNKNOWN         HealthCheckResponse_ServingStatus = 0
	HealthCheckResponse_SERVING         HealthCheckResponse_ServingStatus = 1
	HealthCheckResponse_NOT_SERVING     HealthCheckResponse_ServingStatus = 2
	HealthCheckResponse_SERVICE_UNKNOWN HealthCheckResponse_ServingStatus = 3 // Used only by the Watch method.
)

// Enum value maps for HealthCheckResponse_ServingStatus.
var (
	HealthCheckResponse_ServingStatus_name = map[int32]string{
		0: "UNKNOWN",
		1: "SERVING",
		2: "NOT_SERVING",
		3: "SERVICE_UNKNOWN",
	}
	HealthCheckResponse_ServingStatus_value = map[string]int32{
		"UNKNOWN":         0,
		"SERVING":         1,
		"NOT_SERVING":     2,
		"SERVICE_UNKNOWN": 3,
	}
)

func (x HealthCheckResponse_ServingStatus) Enum() *HealthCheckResponse_ServingStatus {
	p := new(HealthCheckResponse_ServingStatus)
	*p = x
	return p
}

func (x HealthCheckResponse_ServingStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (HealthCheckResponse_ServingStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_atelerix_proto_enumTypes[0].Descriptor()
}

func (HealthCheckResponse_ServingStatus) Type() protoreflect.EnumType {
	return &file_atelerix_proto_enumTypes[0]
}

func (x HealthCheckResponse_ServingStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use HealthCheckResponse_ServingStatus.Descriptor instead.
func (HealthCheckResponse_ServingStatus) EnumDescriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{8, 0}
}

// Request for retrieving checkpoints
type GetCheckpointsRequest struct {
	state                               protoimpl.MessageState `protogen:"open.v1"`
	ChainId                             uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	LatestPreviousCheckpointBlockNumber uint64                 `protobuf:"varint,2,opt,name=latest_previous_checkpoint_block_number,json=latestPreviousCheckpointBlockNumber,proto3" json:"latest_previous_checkpoint_block_number,omitempty"`
	Limit                               *uint32                `protobuf:"varint,3,opt,name=limit,proto3,oneof" json:"limit,omitempty"` // Maximum number of checkpoints to return
	unknownFields                       protoimpl.UnknownFields
	sizeCache                           protoimpl.SizeCache
}

func (x *GetCheckpointsRequest) Reset() {
	*x = GetCheckpointsRequest{}
	mi := &file_atelerix_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCheckpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCheckpointsRequest) ProtoMessage() {}

func (x *GetCheckpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCheckpointsRequest.ProtoReflect.Descriptor instead.
func (*GetCheckpointsRequest) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{0}
}

func (x *GetCheckpointsRequest) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *GetCheckpointsRequest) GetLatestPreviousCheckpointBlockNumber() uint64 {
	if x != nil {
		return x.LatestPreviousCheckpointBlockNumber
	}
	return 0
}

func (x *GetCheckpointsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

type GetChainIDResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetChainIDResponse) Reset() {
	*x = GetChainIDResponse{}
	mi := &file_atelerix_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetChainIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetChainIDResponse) ProtoMessage() {}

func (x *GetChainIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetChainIDResponse.ProtoReflect.Descriptor instead.
func (*GetChainIDResponse) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{1}
}

func (x *GetChainIDResponse) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

// Request for retrieving external transactions
type GetExternalTransactionsRequest struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	LatestPreviousBlockNumber uint64                 `protobuf:"varint,1,opt,name=latest_previous_block_number,json=latestPreviousBlockNumber,proto3" json:"latest_previous_block_number,omitempty"` // The block number from which to start retrieving transactions
	Limit                     *uint32                `protobuf:"varint,2,opt,name=limit,proto3,oneof" json:"limit,omitempty"`                                                                        // Maximum number of transactions to return
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *GetExternalTransactionsRequest) Reset() {
	*x = GetExternalTransactionsRequest{}
	mi := &file_atelerix_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalTransactionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalTransactionsRequest) ProtoMessage() {}

func (x *GetExternalTransactionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalTransactionsRequest.ProtoReflect.Descriptor instead.
func (*GetExternalTransactionsRequest) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{2}
}

func (x *GetExternalTransactionsRequest) GetLatestPreviousBlockNumber() uint64 {
	if x != nil {
		return x.LatestPreviousBlockNumber
	}
	return 0
}

func (x *GetExternalTransactionsRequest) GetLimit() uint32 {
	if x != nil && x.Limit != nil {
		return *x.Limit
	}
	return 0
}

// Response message containing checkpoints
type CheckpointResponse struct {
	state         protoimpl.MessageState           `protogen:"open.v1"`
	Checkpoints   []*CheckpointResponse_Checkpoint `protobuf:"bytes,1,rep,name=checkpoints,proto3" json:"checkpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckpointResponse) Reset() {
	*x = CheckpointResponse{}
	mi := &file_atelerix_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse) ProtoMessage() {}

func (x *CheckpointResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse.ProtoReflect.Descriptor instead.
func (*CheckpointResponse) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{3}
}

func (x *CheckpointResponse) GetCheckpoints() []*CheckpointResponse_Checkpoint {
	if x != nil {
		return x.Checkpoints
	}
	return nil
}

// Helper message for representing byte arrays (to support [][]byte)
type ByteArray struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ByteArray) Reset() {
	*x = ByteArray{}
	mi := &file_atelerix_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ByteArray) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ByteArray) ProtoMessage() {}

func (x *ByteArray) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ByteArray.ProtoReflect.Descriptor instead.
func (*ByteArray) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{4}
}

func (x *ByteArray) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

// External transaction structure
type ExternalTransaction struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ChainId       uint64                 `protobuf:"varint,1,opt,name=chain_id,json=chainId,proto3" json:"chain_id,omitempty"`
	Tx            []byte                 `protobuf:"bytes,2,opt,name=tx,proto3" json:"tx,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExternalTransaction) Reset() {
	*x = ExternalTransaction{}
	mi := &file_atelerix_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExternalTransaction) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExternalTransaction) ProtoMessage() {}

func (x *ExternalTransaction) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExternalTransaction.ProtoReflect.Descriptor instead.
func (*ExternalTransaction) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{5}
}

func (x *ExternalTransaction) GetChainId() uint64 {
	if x != nil {
		return x.ChainId
	}
	return 0
}

func (x *ExternalTransaction) GetTx() []byte {
	if x != nil {
		return x.Tx
	}
	return nil
}

// Response for transaction batch creation
type CreateInternalTransactionsBatchResponse struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BatchHash            []byte                 `protobuf:"bytes,1,opt,name=batch_hash,json=batchHash,proto3" json:"batch_hash,omitempty"`                                  // Hash of the transaction batch
	InternalTransactions []*ByteArray           `protobuf:"bytes,2,rep,name=internal_transactions,json=internalTransactions,proto3" json:"internal_transactions,omitempty"` // Sorted Appchain execution internal transactions
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *CreateInternalTransactionsBatchResponse) Reset() {
	*x = CreateInternalTransactionsBatchResponse{}
	mi := &file_atelerix_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateInternalTransactionsBatchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateInternalTransactionsBatchResponse) ProtoMessage() {}

func (x *CreateInternalTransactionsBatchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateInternalTransactionsBatchResponse.ProtoReflect.Descriptor instead.
func (*CreateInternalTransactionsBatchResponse) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{6}
}

func (x *CreateInternalTransactionsBatchResponse) GetBatchHash() []byte {
	if x != nil {
		return x.BatchHash
	}
	return nil
}

func (x *CreateInternalTransactionsBatchResponse) GetInternalTransactions() []*ByteArray {
	if x != nil {
		return x.InternalTransactions
	}
	return nil
}

// Response for external transactions
// Response for external transactions (supports multiple blocks)
type GetExternalTransactionsResponse struct {
	state         protoimpl.MessageState                               `protogen:"open.v1"`
	Blocks        []*GetExternalTransactionsResponse_BlockTransactions `protobuf:"bytes,1,rep,name=blocks,proto3" json:"blocks,omitempty"` // Список блоков с транзакциями
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetExternalTransactionsResponse) Reset() {
	*x = GetExternalTransactionsResponse{}
	mi := &file_atelerix_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalTransactionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalTransactionsResponse) ProtoMessage() {}

func (x *GetExternalTransactionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalTransactionsResponse.ProtoReflect.Descriptor instead.
func (*GetExternalTransactionsResponse) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{7}
}

func (x *GetExternalTransactionsResponse) GetBlocks() []*GetExternalTransactionsResponse_BlockTransactions {
	if x != nil {
		return x.Blocks
	}
	return nil
}

// Health check response message
type HealthCheckResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Status        HealthCheckResponse_ServingStatus `protobuf:"varint,1,opt,name=status,proto3,enum=atelerix.HealthCheckResponse_ServingStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_atelerix_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{8}
}

func (x *HealthCheckResponse) GetStatus() HealthCheckResponse_ServingStatus {
	if x != nil {
		return x.Status
	}
	return HealthCheckResponse_UNKNOWN
}

type CheckpointResponse_Checkpoint struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	LatestBlockNumber  uint64                 `protobuf:"varint,1,opt,name=latest_block_number,json=latestBlockNumber,proto3" json:"latest_block_number,omitempty"` // Latest Appchain block included in the checkpoint
	StateRoot          []byte                 `protobuf:"bytes,2,opt,name=state_root,json=stateRoot,proto3" json:"state_root,omitempty"`
	BlockHash          []byte                 `protobuf:"bytes,3,opt,name=block_hash,json=blockHash,proto3" json:"block_hash,omitempty"`
	ExternalTxRootHash []byte                 `protobuf:"bytes,4,opt,name=external_tx_root_hash,json=externalTxRootHash,proto3" json:"external_tx_root_hash,omitempty"` // Format & DB config for external transactions
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *CheckpointResponse_Checkpoint) Reset() {
	*x = CheckpointResponse_Checkpoint{}
	mi := &file_atelerix_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckpointResponse_Checkpoint) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckpointResponse_Checkpoint) ProtoMessage() {}

func (x *CheckpointResponse_Checkpoint) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckpointResponse_Checkpoint.ProtoReflect.Descriptor instead.
func (*CheckpointResponse_Checkpoint) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{3, 0}
}

func (x *CheckpointResponse_Checkpoint) GetLatestBlockNumber() uint64 {
	if x != nil {
		return x.LatestBlockNumber
	}
	return 0
}

func (x *CheckpointResponse_Checkpoint) GetStateRoot() []byte {
	if x != nil {
		return x.StateRoot
	}
	return nil
}

func (x *CheckpointResponse_Checkpoint) GetBlockHash() []byte {
	if x != nil {
		return x.BlockHash
	}
	return nil
}

func (x *CheckpointResponse_Checkpoint) GetExternalTxRootHash() []byte {
	if x != nil {
		return x.ExternalTxRootHash
	}
	return nil
}

type GetExternalTransactionsResponse_BlockTransactions struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	BlockNumber          uint64                 `protobuf:"varint,1,opt,name=block_number,json=blockNumber,proto3" json:"block_number,omitempty"`                             // Блок, к которому относятся транзакции
	TransactionsRootHash []byte                 `protobuf:"bytes,2,opt,name=transactions_root_hash,json=transactionsRootHash,proto3" json:"transactions_root_hash,omitempty"` // Хеш всех транзакций блока
	ExternalTransactions []*ExternalTransaction `protobuf:"bytes,3,rep,name=external_transactions,json=externalTransactions,proto3" json:"external_transactions,omitempty"`   // Список транзакций для блока
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *GetExternalTransactionsResponse_BlockTransactions) Reset() {
	*x = GetExternalTransactionsResponse_BlockTransactions{}
	mi := &file_atelerix_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetExternalTransactionsResponse_BlockTransactions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetExternalTransactionsResponse_BlockTransactions) ProtoMessage() {}

func (x *GetExternalTransactionsResponse_BlockTransactions) ProtoReflect() protoreflect.Message {
	mi := &file_atelerix_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetExternalTransactionsResponse_BlockTransactions.ProtoReflect.Descriptor instead.
func (*GetExternalTransactionsResponse_BlockTransactions) Descriptor() ([]byte, []int) {
	return file_atelerix_proto_rawDescGZIP(), []int{7, 0}
}

func (x *GetExternalTransactionsResponse_BlockTransactions) GetBlockNumber() uint64 {
	if x != nil {
		return x.BlockNumber
	}
	return 0
}

func (x *GetExternalTransactionsResponse_BlockTransactions) GetTransactionsRootHash() []byte {
	if x != nil {
		return x.TransactionsRootHash
	}
	return nil
}

func (x *GetExternalTransactionsResponse_BlockTransactions) GetExternalTransactions() []*ExternalTransaction {
	if x != nil {
		return x.ExternalTransactions
	}
	return nil
}

var File_atelerix_proto protoreflect.FileDescriptor

const file_atelerix_proto_rawDesc = "" +
	"\n" +
	"\x0eatelerix.proto\x12\batelerix\x1a\x1bgoogle/protobuf/empty.proto\"\xad\x01\n" +
	"\x15GetCheckpointsRequest\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12T\n" +
	"'latest_previous_checkpoint_block_number\x18\x02 \x01(\x04R#latestPreviousCheckpointBlockNumber\x12\x19\n" +
	"\x05limit\x18\x03 \x01(\rH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"/\n" +
	"\x12GetChainIDResponse\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\"\x86\x01\n" +
	"\x1eGetExternalTransactionsRequest\x12?\n" +
	"\x1clatest_previous_block_number\x18\x01 \x01(\x04R\x19latestPreviousBlockNumber\x12\x19\n" +
	"\x05limit\x18\x02 \x01(\rH\x00R\x05limit\x88\x01\x01B\b\n" +
	"\x06_limit\"\x8f\x02\n" +
	"\x12CheckpointResponse\x12I\n" +
	"\vcheckpoints\x18\x01 \x03(\v2'.atelerix.CheckpointResponse.CheckpointR\vcheckpoints\x1a\xad\x01\n" +
	"\n" +
	"Checkpoint\x12.\n" +
	"\x13latest_block_number\x18\x01 \x01(\x04R\x11latestBlockNumber\x12\x1d\n" +
	"\n" +
	"state_root\x18\x02 \x01(\fR\tstateRoot\x12\x1d\n" +
	"\n" +
	"block_hash\x18\x03 \x01(\fR\tblockHash\x121\n" +
	"\x15external_tx_root_hash\x18\x04 \x01(\fR\x12externalTxRootHash\"\x1f\n" +
	"\tByteArray\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"@\n" +
	"\x13ExternalTransaction\x12\x19\n" +
	"\bchain_id\x18\x01 \x01(\x04R\achainId\x12\x0e\n" +
	"\x02tx\x18\x02 \x01(\fR\x02tx\"\x92\x01\n" +
	"'CreateInternalTransactionsBatchResponse\x12\x1d\n" +
	"\n" +
	"batch_hash\x18\x01 \x01(\fR\tbatchHash\x12H\n" +
	"\x15internal_transactions\x18\x02 \x03(\v2\x13.atelerix.ByteArrayR\x14internalTransactions\"\xb9\x02\n" +
	"\x1fGetExternalTransactionsResponse\x12S\n" +
	"\x06blocks\x18\x01 \x03(\v2;.atelerix.GetExternalTransactionsResponse.BlockTransactionsR\x06blocks\x1a\xc0\x01\n" +
	"\x11BlockTransactions\x12!\n" +
	"\fblock_number\x18\x01 \x01(\x04R\vblockNumber\x124\n" +
	"\x16transactions_root_hash\x18\x02 \x01(\fR\x14transactionsRootHash\x12R\n" +
	"\x15external_transactions\x18\x03 \x03(\v2\x1d.atelerix.ExternalTransactionR\x14externalTransactions\"\xab\x01\n" +
	"\x13HealthCheckResponse\x12C\n" +
	"\x06status\x18\x01 \x01(\x0e2+.atelerix.HealthCheckResponse.ServingStatusR\x06status\"O\n" +
	"\rServingStatus\x12\v\n" +
	"\aUNKNOWN\x10\x00\x12\v\n" +
	"\aSERVING\x10\x01\x12\x0f\n" +
	"\vNOT_SERVING\x10\x02\x12\x13\n" +
	"\x0fSERVICE_UNKNOWN\x10\x032\xfc\x02\n" +
	"\aEmitter\x12O\n" +
	"\x0eGetCheckpoints\x12\x1f.atelerix.GetCheckpointsRequest\x1a\x1c.atelerix.CheckpointResponse\x12l\n" +
	"\x1fCreateInternalTransactionsBatch\x12\x16.google.protobuf.Empty\x1a1.atelerix.CreateInternalTransactionsBatchResponse\x12n\n" +
	"\x17GetExternalTransactions\x12(.atelerix.GetExternalTransactionsRequest\x1a).atelerix.GetExternalTransactionsResponse\x12B\n" +
	"\n" +
	"GetChainID\x12\x16.google.protobuf.Empty\x1a\x1c.atelerix.GetChainIDResponse2\x8a\x01\n" +
	"\x06Health\x12>\n" +
	"\x05Check\x12\x16.google.protobuf.Empty\x1a\x1d.atelerix.HealthCheckResponse\x12@\n" +
	"\x05Watch\x12\x16.google.protobuf.Empty\x1a\x1d.atelerix.HealthCheckResponse0\x01B\x16Z\x14./proto;emitterprotob\x06proto3"

var (
	file_atelerix_proto_rawDescOnce sync.Once
	file_atelerix_proto_rawDescData []byte
)

func file_atelerix_proto_rawDescGZIP() []byte {
	file_atelerix_proto_rawDescOnce.Do(func() {
		file_atelerix_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_atelerix_proto_rawDesc), len(file_atelerix_proto_rawDesc)))
	})
	return file_atelerix_proto_rawDescData
}

var file_atelerix_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_atelerix_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_atelerix_proto_goTypes = []any{
	(HealthCheckResponse_ServingStatus)(0),                    // 0: atelerix.HealthCheckResponse.ServingStatus
	(*GetCheckpointsRequest)(nil),                             // 1: atelerix.GetCheckpointsRequest
	(*GetChainIDResponse)(nil),                                // 2: atelerix.GetChainIDResponse
	(*GetExternalTransactionsRequest)(nil),                    // 3: atelerix.GetExternalTransactionsRequest
	(*CheckpointResponse)(nil),                                // 4: atelerix.CheckpointResponse
	(*ByteArray)(nil),                                         // 5: atelerix.ByteArray
	(*ExternalTransaction)(nil),                               // 6: atelerix.ExternalTransaction
	(*CreateInternalTransactionsBatchResponse)(nil),           // 7: atelerix.CreateInternalTransactionsBatchResponse
	(*GetExternalTransactionsResponse)(nil),                   // 8: atelerix.GetExternalTransactionsResponse
	(*HealthCheckResponse)(nil),                               // 9: atelerix.HealthCheckResponse
	(*CheckpointResponse_Checkpoint)(nil),                     // 10: atelerix.CheckpointResponse.Checkpoint
	(*GetExternalTransactionsResponse_BlockTransactions)(nil), // 11: atelerix.GetExternalTransactionsResponse.BlockTransactions
	(*emptypb.Empty)(nil),                                     // 12: google.protobuf.Empty
}
var file_atelerix_proto_depIdxs = []int32{
	10, // 0: atelerix.CheckpointResponse.checkpoints:type_name -> atelerix.CheckpointResponse.Checkpoint
	5,  // 1: atelerix.CreateInternalTransactionsBatchResponse.internal_transactions:type_name -> atelerix.ByteArray
	11, // 2: atelerix.GetExternalTransactionsResponse.blocks:type_name -> atelerix.GetExternalTransactionsResponse.BlockTransactions
	0,  // 3: atelerix.HealthCheckResponse.status:type_name -> atelerix.HealthCheckResponse.ServingStatus
	6,  // 4: atelerix.GetExternalTransactionsResponse.BlockTransactions.external_transactions:type_name -> atelerix.ExternalTransaction
	1,  // 5: atelerix.Emitter.GetCheckpoints:input_type -> atelerix.GetCheckpointsRequest
	12, // 6: atelerix.Emitter.CreateInternalTransactionsBatch:input_type -> google.protobuf.Empty
	3,  // 7: atelerix.Emitter.GetExternalTransactions:input_type -> atelerix.GetExternalTransactionsRequest
	12, // 8: atelerix.Emitter.GetChainID:input_type -> google.protobuf.Empty
	12, // 9: atelerix.Health.Check:input_type -> google.protobuf.Empty
	12, // 10: atelerix.Health.Watch:input_type -> google.protobuf.Empty
	4,  // 11: atelerix.Emitter.GetCheckpoints:output_type -> atelerix.CheckpointResponse
	7,  // 12: atelerix.Emitter.CreateInternalTransactionsBatch:output_type -> atelerix.CreateInternalTransactionsBatchResponse
	8,  // 13: atelerix.Emitter.GetExternalTransactions:output_type -> atelerix.GetExternalTransactionsResponse
	2,  // 14: atelerix.Emitter.GetChainID:output_type -> atelerix.GetChainIDResponse
	9,  // 15: atelerix.Health.Check:output_type -> atelerix.HealthCheckResponse
	9,  // 16: atelerix.Health.Watch:output_type -> atelerix.HealthCheckResponse
	11, // [11:17] is the sub-list for method output_type
	5,  // [5:11] is the sub-list for method input_type
	5,  // [5:5] is the sub-list for extension type_name
	5,  // [5:5] is the sub-list for extension extendee
	0,  // [0:5] is the sub-list for field type_name
}

func init() { file_atelerix_proto_init() }
func file_atelerix_proto_init() {
	if File_atelerix_proto != nil {
		return
	}
	file_atelerix_proto_msgTypes[0].OneofWrappers = []any{}
	file_atelerix_proto_msgTypes[2].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_atelerix_proto_rawDesc), len(file_atelerix_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_atelerix_proto_goTypes,
		DependencyIndexes: file_atelerix_proto_depIdxs,
		EnumInfos:         file_atelerix_proto_enumTypes,
		MessageInfos:      file_atelerix_proto_msgTypes,
	}.Build()
	File_atelerix_proto = out.File
	file_atelerix_proto_goTypes = nil
	file_atelerix_proto_depIdxs = nil
}
