[package]
name = "rustsdk"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.13.0"
prost = "0.13.5"
prost-types = "0.13"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
tokio-util = "0.7"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proptest = "1.6"
thiserror = "2"
libmdbx = { package = "libmdbx", version = "0.5", features = ["cbor", "orm"] }
bincode = "1.3.3"
async-trait = "0.1"
log = "0.4"
env_logger = "0.11"
tempfile = "3.19"
anyhow = "1.0"
once_cell = "1.21"
arrayref = "0.3"
ethereum-types = { version = "0.15", default-features = false, features = [
  "serialize",
  "std",
] }
ethnum = { version = "1", features = ["serde"] }
byteorder = "1"
bytes = { version = "1", features = ["serde"] }
bytesize = "2"

[build-dependencies]
tonic-build = "0.13.0"
tokio-test = "0.4"

[lib]
crate-type = ["lib"]