[package]
name = "rustsdk"
version = "0.1.0"
edition = "2024"

[dependencies]
tonic = "0.12.3"
prost = "0.13.5"
tokio = { version = "1", features = ["full"] }
tokio-stream = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
proptest = "1.6"
thiserror = "2"
mdbx = { package = "libmdbx", version = "0.5", features = ["cbor", "orm"] }
bincode = "2"

[build-dependencies]
tonic-build = "0.12"

[lib]
crate-type = ["lib"]